{{- $ca := genCA "polarismesh-ca" 3650 -}}
{{- $cn := printf "%s.%s.svc" ( .Values.controller.webhook.service ) .Release.Namespace }}
{{- $cert := genSignedCert $cn nil (list $cn) 3650 $ca -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (include "polaris-controller.controller.fullname" .)}}
{{- if $existingSecret }}
{{- $ca_cert := index $existingSecret.data "ca-cert.pem" | b64dec }}
{{- $ca_key := index $existingSecret.data "ca-key.pem" | b64dec }}
{{- $cert_cert := index $existingSecret.data "cert.pem" | b64dec }}
{{- $cert_key := index $existingSecret.data "key.pem" | b64dec }}
{{- $ca = dict "Cert" $ca_cert "Key" $ca_key }}
{{- $cert = dict "Cert" $cert_cert "Key" $cert_key }}
{{- end }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "polaris-controller.controller.fullname" . }}-injector
  labels:
    app: sidecar-injector
webhooks:
  - name: ns.injector.polarismesh.cn
    clientConfig:
      service:
        name: {{ .Values.controller.webhook.service }}
        namespace: polaris-system
        path: "/inject"
      caBundle:  {{ b64enc $ca.Cert }}
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1"]
    sideEffects: "None"
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        polarismesh.cn/inject: enabled
  - name: allowlist.polarismesh.cn
    clientConfig:
      service:
        name: {{ .Values.controller.webhook.service }}
        namespace: polaris-system
        path: "/inject"
      caBundle:  {{ b64enc $ca.Cert }}
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1"]
    sideEffects: "None"
    failurePolicy: Fail
    objectSelector:
      matchLabels:
        polarismesh.cn/inject: enabled

---

apiVersion: v1
data:
  cert.pem: {{ b64enc $cert.Cert }}
  key.pem: {{ b64enc $cert.Key }}
  ca-cert.pem: {{ b64enc $ca.Cert }}
  ca-key.pem: {{ b64enc $ca.Key }}
kind: Secret
metadata:
  name: {{ include "polaris-controller.controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
