apiVersion: v1
kind: ConfigMap
metadata:
  name: polaris-controller-config
  namespace: polaris-system
data:
  mesh: |-
    logger:
      default:
        rotateOutputPath: logs/polaris-default.log
        errorRotateOutputPath: logs/polaris-default-error.log
        rotationMaxSize: 100
        rotationMaxBackups: 10
        rotationMaxAge: 7
        outputLevel: info
        outputPaths:
          - stdout
        errorOutputPaths:
          - stderr
      synccm:
        rotateOutputPath: logs/polaris-synccm.log
        errorRotateOutputPath: logs/polaris-synccm-error.log
        rotationMaxSize: 100
        rotationMaxBackups: 10
        rotationMaxAge: 7
        outputLevel: info
        outputPaths:
          - stdout
        errorOutputPaths:
          - stderr
      syncnaming:
        rotateOutputPath: logs/polaris-syncnaming.log
        errorRotateOutputPath: logs/polaris-syncnaming-error.log
        rotationMaxSize: 100
        rotationMaxBackups: 10
        rotationMaxAge: 7
        outputLevel: info
        outputPaths:
          - stdout
        errorOutputPaths:
          - stderr
      syncconfig:
        rotateOutputPath: logs/polaris-syncconfig.log
        errorRotateOutputPath: logs/polaris-syncconfig-error.log
        rotationMaxSize: 100
        rotationMaxBackups: 10
        rotationMaxAge: 7
        outputLevel: info
        outputPaths:
          - stdout
        errorOutputPaths:
          - stderr
      inject:
        rotateOutputPath: logs/polaris-inject.log
        errorRotateOutputPath: logs/polaris-inject-error.log
        rotationMaxSize: 100
        rotationMaxBackups: 10
        rotationMaxAge: 7
        outputLevel: info
        outputPaths:
          - stdout
        errorOutputPaths:
          - stderr
    # k8s cluster name
    clusterName: "#CLUSTER_NAME#"
    # polaris-sidecar 注入的默认启动模式, 可以配置 mesh 或者 dns
    sidecarInject:
      mode: "mesh"
    # service sync
    serviceSync:
      enable: true
      mode: "all"
      serverAddress: #POLARIS_HOST#
      # 北极星开启鉴权时需要配置
      accessToken: #POLARIS_TOKEN#
    configSync:
      enable: true
      serverAddress: #POLARIS_HOST#
      # 北极星开启鉴权时需要配置
      accessToken: #POLARIS_TOKEN#
      allowDelete: false
      # 配置同步方向: kubernetesToPolaris|polarisToKubernetes|both
      syncDirection: both
      defaultGroup: "#CLUSTER_NAME#"
    defaultConfig:
      proxyMetadata:
        serverAddress: #POLARIS_HOST#