apiVersion: v1
kind: ConfigMap
metadata:
  name: polaris-controller-config
  namespace: polaris-system
data:
  mesh: |-
    logger:
      default:
        rotateOutputPath: logs/polaris-default.log
        errorRotateOutputPath: logs/polaris-default-error.log
        rotationMaxSize: 100
        rotationMaxBackups: 10
        rotationMaxAge: 7
        outputLevel: info
        outputPaths:
          - stdout
        errorOutputPaths:
          - stderr
      synccm:
        rotateOutputPath: logs/polaris-synccm.log
        errorRotateOutputPath: logs/polaris-synccm-error.log
        rotationMaxSize: 100
        rotationMaxBackups: 10
        rotationMaxAge: 7
        outputLevel: info
        outputPaths:
          - stdout
        errorOutputPaths:
          - stderr
      syncnaming:
        rotateOutputPath: logs/polaris-syncnaming.log
        errorRotateOutputPath: logs/polaris-syncnaming-error.log
        rotationMaxSize: 100
        rotationMaxBackups: 10
        rotationMaxAge: 7
        outputLevel: info
        outputPaths:
          - stdout
        errorOutputPaths:
          - stderr
      syncconfig:
        rotateOutputPath: logs/polaris-syncconfig.log
        errorRotateOutputPath: logs/polaris-syncconfig-error.log
        rotationMaxSize: 100
        rotationMaxBackups: 10
        rotationMaxAge: 7
        outputLevel: info
        outputPaths:
          - stdout
        errorOutputPaths:
          - stderr
      inject:
        rotateOutputPath: logs/polaris-inject.log
        errorRotateOutputPath: logs/polaris-inject-error.log
        rotationMaxSize: 100
        rotationMaxBackups: 10
        rotationMaxAge: 7
        outputLevel: info
        outputPaths:
          - stdout
        errorOutputPaths:
          - stderr
    # 北极星服务端地址
    serverAddress: #POLARIS_HOST#
    # 北极星服务端token(北极星开启鉴权时需要配置)
    accessToken: "#POLARIS_TOKEN#"
    # 北极星主账户ID
    operator: #POLARIS_OPERATOR#
    # k8s cluster name
    clusterName: "#CLUSTER_NAME#"
    # polaris-sidecar 注入的默认启动模式, 可以配置 java-agent, mesh 或者 dns
    sidecarInject:
      mode: ""
    # service sync
    serviceSync:
      mode: #SYNC_MODE#
    configSync:
      enable: false
      allowDelete: false
      syncDirection: both
      defaultGroup: "#CLUSTER_NAME#"
    defaultConfig:
      proxyMetadata:
        serverAddress: #POLARIS_HOST#
        clusterName: #CLUSTER_NAME#
