apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    qcloud-app: polaris-controller
  name: polaris-controller
  namespace: polaris-system
spec:
  replicas: 1
  revisionHistoryLimit: 10
  serviceName: polaris-controller
  selector:
    matchLabels:
      k8s-app: polaris-controller
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: polaris-controller
        app: sidecar-injector
    spec:
      containers:
        - name: polaris-controller
          image: polarismesh/polaris-controller:#CONTROLLER_VERSION#
          command: ["./polaris-controller"]
          args: ["--min-resync-period=60s",
                 "--leader-elect-namespace=polaris-system",
                 "--concurrency-polaris-size=100",
                 "--leader-elect=true"
          ]
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /polaris-controller/logs
              name: logs
            - name: certs
              mountPath: /etc/polaris-inject/certs
              readOnly: true
            - name: inject-config
              mountPath: /etc/polaris-inject/inject
              readOnly: true
            - name: config-volume
              mountPath: /etc/polaris-inject/config
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      serviceAccountName: polaris-controller
      volumes:
        - name: certs
          secret:
            secretName: polaris-sidecar-injector
        - name: inject-config
          configMap:
            name: polaris-sidecar-injector
            items:
              - key: mesh-config
                path: mesh-config
              - key: dns-config
                path: dns-config
              - key: values
                path: values
        - name: config-volume
          configMap:
            name: injector-mesh
        - hostPath:
            path: /data/polaris-controller/logs
            type: "DirectoryOrCreate"
          name: logs