apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    {{- include "polaris-controller.controller.labels" . | nindent 4 }}
  name: {{ include "polaris-controller.controller.fullname" . }}
  namespace: polaris-system
spec:
  replicas: 1
  revisionHistoryLimit: 10
  serviceName: polaris-controller
  selector:
    matchLabels:
      {{- include "polaris-controller.controller.selectorLabels" . | nindent 6 }}
  updateStrategy:
    rollingUpdate:
      partition: 0
  template:
    metadata:
      labels:
      {{- include "polaris-controller.controller.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: polaris-controller
          image: {{ template "polaris-controller.controller.image" . }}
          command: ["./polaris-controller"]
          args: ["--min-resync-period=60s",
                 "--leader-elect-namespace=polaris-system",
                 "--concurrency-polaris-size=100",
                 "--leader-elect=true"
          ]
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          resources:
            limits:
              cpu: {{ .Values.controller.limit.cpu }}
              memory: {{ .Values.controller.limit.memory }}
          volumeMounts:
            - mountPath: /polaris-controller/log
              name: log
            - name: certs
              mountPath: /etc/polaris-inject/certs
              readOnly: true
            - name: inject-config
              mountPath: /etc/polaris-inject/inject
              readOnly: true
            - name: config-volume
              mountPath: /etc/polaris-inject/config
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      serviceAccountName: {{ include "polaris-controller.controller.fullname" . }}
      volumes:
        - name: certs
          secret:
            secretName: {{ include "polaris-controller.controller.fullname" . }}
        - name: inject-config
          configMap:
            name: {{ include "polaris-controller.controller.fullname" . }}-sidecar
            items:
              - key: mesh-config
                path: mesh-config
              - key: dns-config
                path: dns-config
              - key: java-agent-config
                path: java-agent-config
              - key: values
                path: values
        - name: config-volume
          configMap:
            name: {{ include "polaris-controller.controller.fullname" . }}-mesh
        - hostPath:
            path: /data/polaris-controller/log
            type: "DirectoryOrCreate"
          name: logs