apiVersion: v1
kind: ConfigMap
metadata:
  name: injector-mesh
  namespace: polaris-system
data:
  mesh: |-
    # k8s cluster name
    clusterName: "default"
    # polaris-sidecar 注入的默认启动模式, 可以配置 mesh 或者 dns
    sidecarInject:
      mode: "mesh"
    # service sync
    serviceSync:
      mode: "all"
      serverAddress: "polaris-server address"
      # 北极星开启鉴权时需要配置
      accessToken: ""
    defaultConfig:
      proxyMetadata:
        serverAddress: "polaris-server address"