apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "polaris-controller.controller.fullname" . }}-sidecar
  namespace: polaris-system
  labels:
    app: sidecar-injector
data:
  values: |-
    {"clusterResources":true,"global":{"arch":{"amd64":2,"ppc64le":2,"s390x":2},"configNamespace":"polaris-system","configValidation":"false","controlPlaneSecurityEnabled":true,"defaultNodeSelector":{},"defaultPodDisruptionBudget":{"enabled":true},"defaultResources":{"requests":{"cpu":"10m"}},"disablePolicyChecks":true,"enableHelmTest":false,"enableTracing":true,"hub":"istio","imagePullPolicy":"Always","imagePullSecrets":[],"istioNamespace":"polaris-system","k8sIngress":{"enableHttps":false,"enabled":false,"gatewayName":"ingressgateway"},"localityLbSetting":{"enabled":true},"logAsJson":false,"logging":{"level":"default:info"},"meshExpansion":{"enabled":false,"useILB":false},"meshID":"","meshNetworks":{},"mtls":{"enabled":false},"multiCluster":{"enabled":false},"oneNamespace":false,"outboundTrafficPolicy":{"mode":"ALLOW_ANY"},"policyCheckFailOpen":false,"policyNamespace":"polaris-system","priorityClassName":"","prometheusNamespace":"polaris-system","proxy":{"accessLogEncoding":"TEXT","accessLogFile":"","accessLogFormat":"","autoInject":"enabled","clusterDomain":"cluster.local","componentLogLevel":"misc:error","concurrency":2,"dnsRefreshRate":"300s","enableCoreDump":false,"envoyAccessLogService":{"enabled":false,"host":null,"port":null},"envoyMetricsService":{"enabled":false,"host":null,"port":null},"envoyStatsd":{"enabled":false,"host":null,"port":null},"excludeIPRanges":"","excludeInboundPorts":"","excludeOutboundPorts":"","image":"proxyv2","includeIPRanges":"*","includeInboundPorts":"*","kubevirtInterfaces":"","logLevel":"warning","privileged":false,"protocolDetectionTimeout":"10ms","readinessFailureThreshold":30,"readinessInitialDelaySeconds":1,"readinessPeriodSeconds":2,"resources":{"limits":{"cpu":"2000m","memory":"1024Mi"},"requests":{"cpu":"100m","memory":"128Mi"}},"statusPort":15020,"tag":"1.7.0","tracer":"zipkin"},"proxy_init":{"image":"proxyv2","resources":{"limits":{"cpu":"100m","memory":"50Mi"},"requests":{"cpu":"10m","memory":"10Mi"}}},"sds":{"enabled":false,"udsPath":""},"tag":"1.5.8","telemetryNamespace":"polaris-system","tracer":{"datadog":{"address":"$(HOST_IP):8126"},"lightstep":{"accessToken":"","address":"","cacertPath":"","secure":true},"zipkin":{"address":""}},"trustDomain":"","useMCP":true,"xdsApiVersion":"v3"},"istio_cni":{"enabled":false},"sidecarInjectorWebhook":{"alwaysInjectSelector":[],"enableAccessLog":false,"enableNamespacesByDefault":false,"image":"sidecar_injector","injectLabel":"istio-injection","neverInjectSelector":[],"nodeSelector":{},"podAntiAffinityLabelSelector":[],"podAntiAffinityTermLabelSelector":[],"replicaCount":2,"rewriteAppHTTPProbe":false,"rollingMaxSurge":"100%","rollingMaxUnavailable":"25%","selfSigned":true,"tolerations":[]},"version":""}

  dns-config: |-
    policy: enabled
    alwaysInjectSelector:
      []

    neverInjectSelector:
      [{"matchLabels":{"polarismesh.cn/inject":"disabled"}}]

    template: |
      containers:
      - image: {{ include "polaris-controller.sidecar.image" . }}
        name: polaris-sidecar
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            drop:
            - ALL
          privileged: true
          readOnlyRootFilesystem: false
          runAsGroup: 1337
          runAsNonRoot: false
          runAsUser: 1337
        imagePullPolicy: {{ .Values.sidecar.image.pullPolicy }}
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 50Mi
        volumeMounts:
          - mountPath: /root/polaris
            defaultMode: 777
            name: polaris-dir
          - mountPath: /root/log
            defaultMode: 777
            name: polaris-log
      initContainers:
      - name: polaris-sidecar-init
        image: {{ include "polaris-controller.sidecar.init.image" . }}
        imagePullPolicy: {{ .Values.sidecar.init.image.pullPolicy }}
        command: ["./start.sh"]
        env:
        - name: RUN_MODE
          value: DNS
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsGroup: 0
          runAsNonRoot: false
          runAsUser: 0
      volumes:
        - name: polaris-sidecar-iptables
          configMap:
            defaultMode: 420
            name: polaris-sidecar-iptables
        - name: polaris-dir
          emptyDir: {}
        - name: polaris-log
          emptyDir: {}

  java-agent-config: |-
    policy: enabled
    alwaysInjectSelector:
      []

    neverInjectSelector:
      [{"matchLabels":{"polarismesh.cn/inject":"disabled"}}]

    template: |
      initContainers:
      - name: polaris-javaagent-init
        image: {{ include "polaris-controller.sidecar.javaagent.image" . }}
        imagePullPolicy: Always
        env:
          - name: JAVA_AGENT_DIR
            value: /app/lib/.polaris/java_agent
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsGroup: 0
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
          - mountPath: /app/lib/.polaris/java_agent
            name: java-agent-dir
      volumes:
        - name: java-agent-dir
          emptyDir: {}



  mesh-config: |-
    policy: enabled
    alwaysInjectSelector:
      []

    neverInjectSelector:
      [{"matchLabels":{"polarismesh.cn/inject":"disabled"}}]

    template: |
      containers:
      - name: envoy
        image: {{ include "polaris-controller.sidecar.envoy.image" . }}
        imagePullPolicy: Always
        command: ["/usr/local/bin/envoy"]
        args: ["-c", "/etc/envoy/envoy.yaml", "--log-path", "/etc/envoy_logs/envoy.log"]
        resources:
        {{ include "configmap-sidecar.envoy_resources" . | nindent 8 }}
        env:
        - name: ENVOY_UID
          value: "1337"
        volumeMounts:
        - mountPath: /etc/envoy
          name: envoy-bootstrap
          readOnly: false
        - mountPath: /etc/envoy_logs
          name: envoy-logs
          readOnly: false
        - mountPath: /tmp/polaris-sidecar
          defaultMode: 777
          name: polaris-socket
      - image: {{ include "polaris-controller.sidecar.image" . }}
        name: polaris-sidecar
        securityContext:
          runAsUser: 1337
          runAsGroup: 1337
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 50Mi
        volumeMounts:
          - mountPath: /root/polaris
            defaultMode: 777
            name: polaris-dir
          - mountPath: /root/log
            defaultMode: 777
            name: polaris-log
          - mountPath: /tmp/polaris-sidecar
            defaultMode: 777
            name: polaris-socket
      initContainers:
      - name: polaris-bootstrap-writer
        image: {{ include "polaris-controller.sidecar.envoy_init.image" . }}
        imagePullPolicy: Always
        env:
        {{ include "configmap-sidecar.bootstrap_envs" . | nindent 10 }}
        volumeMounts:
          - mountPath: /var/lib/data
            name: envoy-bootstrap
          - mountPath: /data/polaris-client-config
            name: polaris-client-config
      - name: polaris-sidecar-init
        image: {{ include "polaris-controller.sidecar.init.image" . }}
        imagePullPolicy: Always
        command: ["./start.sh"]
        env:
        - name: RUN_MODE
          value: MESH
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsGroup: 0
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
          - mountPath: /data/polaris-client-config
            name: polaris-client-config
      volumes:
        - name: polaris-client-config
          emptyDir: {}
        - name: envoy-bootstrap
          emptyDir: {}
        - name: envoy-logs
          emptyDir: {}
        - name: polaris-dir
          emptyDir: {}
        - name: polaris-log
          emptyDir: {}
        - name: polaris-socket
          emptyDir: {}