apiVersion: v1
kind: ServiceAccount
metadata:
  name: polaris-controller
  namespace: polaris-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: polaris-controller
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["create", "update", "get", "list", "watch"]
  - apiGroups:  [""]
    resources: ["pods", "services", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups:  [""]
    resources: ["configmaps"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: polaris-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: polaris-controller
subjects:
  - kind: ServiceAccount
    name: polaris-controller
    namespace: polaris-system
