name: Docker

on:
  release:
    types: [published]

jobs:
  release:
    name: Release Polaris Docker Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.polaris_tag }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          config-inline: |
            insecure-entitlements = [ "network.host" ]

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.POLARIS_DOCKER_NAME }}
          password: ${{ secrets.POLARIS_DOCKER_PASSWORD }}

      - name: Build
        id: build
        env:
          DOCKER_TAG: ${{ steps.get_version.outputs.VERSION }}
        run: |
          make all ORG=polarismesh REPO=polaris-controller IMAGE_TAG=${DOCKER_TAG}
