name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: vert check
      run: bash vert.sh -install && bash vert.sh

    - name: Build polairs-controller
      run: make build

    - name: Test
      run: go mod vendor && go test  -timeout 80m ./... -v -covermode=count -coverprofile=coverage_1.cover

    - name: Upload Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
